backend:
  name: git-gateway
  branch: master 

  
# publish_mode: editorial_workflow


media_folder: "dist/assets/image"
public_folder: "/assets/image"


collections:
  - name: "posts" 
    label: "Post" 
    folder: "src/posts" 
    create: true
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "dateTime"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Image Alt", name: "imgAlt", widget: "string"}
      - {label: "Content", name: "description", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: "posts"}


  - name: "slideshow" 
    label: "Slideshow" 
    folder: "src/slideshow"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: "nature"}
      - {label: "Image 1", name: "img1", widget: "image", required: false}
      - {label: "Image 2", name: "img2", widget: "image", required: false}
      - {label: "Image 3", name: "img3", widget: "image", required: false}
      - {label: "Image 4", name: "img4", widget: "image", required: false}
      - {label: "Image 5", name: "img5", widget: "image", required: false}
      - {label: "Image 6", name: "img6", widget: "image", required: false}
      - {label: "Image 7", name: "img7", widget: "image", required: false}
      - {label: "Image 8", name: "img8", widget: "image", required: false} 
      - {label: "Image 9", name: "img9", widget: "image", required: false}
      - {label: "Image 10", name: "img10", widget: "image", required: false}
     

